### ISSUE TITLE
Indent after closing parenthesis

### ISSUE THREAD

**Issue by phil-blain** [hansec/ide-fortran#14]
Hi, 
Great extension! It's really useful for me. One thing that could be improved is the following (though I don't know if this is more on the Atom side itself...)

When I press 'Return' after the closing parenthesis of a subroutine or function call that is written on multiple lines, the new line is indented to the same indent as the previous line, but it would be better if it would return to the indentation of the line where the subroutine or function was called.
An illustration : 
![indent-arguments](https://user-images.githubusercontent.com/44212482/61725687-3a590180-ad3e-11e9-9a0f-aed3dfc4544a.png)
This is especially annoying if because if you delete all spaces in the newline (line 4 above) and press TAB to indent, the indentation returns to that of the previous line, so the right amount of spaces must be entered manually (or copied from somewhere else) to get the right indentation again.

**Comment by hansec** [comment]
Thanks for the report, but unfortunately that functionality isn't handled by this extension. It might be handled by the "base language package" ([language-fortran](https://atom.io/packages/language-fortran)), but it also might be lower level in Atom somewhere since Atom has a generic indentation handler too. I am not exactly sure.

**Comment by phil-blain** [comment]
Thanks for the pointer. I asked here: dparkins/language-fortran#113
